# Generated by Django 5.0.7 on 2024-08-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='community_covers/'),
        ),
    ]
